[package]
name = "rusefs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
walkdir = "2"
regex = "1"
clap = "3.0.0-beta.2"
config = "0.11"
